/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package View;
import Model.DBConnector;
import Model.Reservation;
import controller.reservation.ReservationController;
import edu.sit.cs.db.CSDbDelegate;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author T.Chan
 */
public class ReservationManagement extends javax.swing.JFrame {
    
    private ReservationController reservationController;
    private DefaultTableModel model;
    String[] col = {"Reserve ID", "Customer ID", "Firstname", "Lastname", "Car ID", "Pick-up Date", "Return Date", "Pick-up Location", "Return Location", "Status"};
    int max_reserve;
    
    /**
     * Creates new form CarManagement
     */
    public ReservationManagement(ReservationController reserveCtrl) {
        reservationController = reserveCtrl;
        
        setTitle("Car Reserve Management");
        setLook();
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        
        refresh();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservation_table = new javax.swing.JTable();
        refresh_button = new javax.swing.JButton();
        search_label = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        label_header = new javax.swing.JLabel();
        search_button = new javax.swing.JButton();
        status_checkbox = new javax.swing.JCheckBox();
        status_combobox = new javax.swing.JComboBox();
        add_reserve_button = new javax.swing.JButton();
        back = new javax.swing.JButton();
        update_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(reservation_table);
        if (reservation_table.getColumnModel().getColumnCount() > 0) {
            reservation_table.getColumnModel().getColumn(0).setResizable(false);
            reservation_table.getColumnModel().getColumn(1).setResizable(false);
            reservation_table.getColumnModel().getColumn(2).setResizable(false);
            reservation_table.getColumnModel().getColumn(3).setResizable(false);
            reservation_table.getColumnModel().getColumn(4).setResizable(false);
            reservation_table.getColumnModel().getColumn(5).setResizable(false);
            reservation_table.getColumnModel().getColumn(6).setResizable(false);
            reservation_table.getColumnModel().getColumn(7).setResizable(false);
            reservation_table.getColumnModel().getColumn(8).setResizable(false);
            reservation_table.getColumnModel().getColumn(9).setResizable(false);
        }

        refresh_button.setText("Refresh");
        refresh_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_buttonActionPerformed(evt);
            }
        });

        search_label.setText("Search :");

        label_header.setText("Reservation List");

        search_button.setText("Search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        status_checkbox.setText("Status");
        status_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_checkboxActionPerformed(evt);
            }
        });

        status_combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pending", "Reserving", "Complete", "Cancel" }));
        status_combobox.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(search_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_button)
                        .addGap(18, 18, 18)
                        .addComponent(status_checkbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(status_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265)
                        .addComponent(refresh_button))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(label_header))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label_header)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(status_checkbox)
                        .addComponent(status_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(refresh_button))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(search_label)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(search_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add_reserve_button.setText("Add Reservation");
        add_reserve_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_reserve_buttonActionPerformed(evt);
            }
        });

        back.setText("Back to Main Menu");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        update_button.setText("Reserving Detail & Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(update_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_reserve_button)
                .addGap(20, 20, 20))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_reserve_button)
                    .addComponent(back)
                    .addComponent(update_button))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void refresh_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_buttonActionPerformed
        refresh();
    }//GEN-LAST:event_refresh_buttonActionPerformed
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        reservationController.goToMainApplication();
    }//GEN-LAST:event_backActionPerformed
    
    private void add_reserve_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_reserve_buttonActionPerformed
        reservationController.runReservationAddingWindow();
    }//GEN-LAST:event_add_reserve_buttonActionPerformed
    
    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        reservationController.runReservationDetailWindow();
    }//GEN-LAST:event_update_buttonActionPerformed
    
    private void status_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_checkboxActionPerformed
        if(status_checkbox.isSelected()){
            status_combobox.setEnabled(true);
        } else {
            status_combobox.setEnabled(false);
        }
    }//GEN-LAST:event_status_checkboxActionPerformed
    
    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
                
        showContent(reservationController.getSearchedReservationList());
        System.out.println("searched table activated.");
        
    }//GEN-LAST:event_search_buttonActionPerformed
    
    public boolean isSelectedStatusCheckbox(){
        return status_checkbox.isSelected();
    }
    
    public String getSelectedStatus(){
        return status_combobox.getSelectedItem().toString();
    }
    
    public String getSearchedText(){
        return search.getText();
    }
    
    public void refresh(){
        showContent(reservationController.getAllReservationList());
        System.out.println("refresh table activated.");
    }
    
    public void showContent(ArrayList<Reservation> reservation_list){
        
        model = new DefaultTableModel(col,0);
        ArrayList<Object[]> table_contents = reservationController.getTableContent(reservation_list);
        for(Object[] row_content : table_contents){
            model.addRow(row_content);
        }
        reservation_table.setModel(model);
        System.out.println("make table success.");
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public void setLook() {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_reserve_button;
    private javax.swing.JButton back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_header;
    private javax.swing.JButton refresh_button;
    private javax.swing.JTable reservation_table;
    private javax.swing.JTextField search;
    private javax.swing.JButton search_button;
    private javax.swing.JLabel search_label;
    private javax.swing.JCheckBox status_checkbox;
    private javax.swing.JComboBox status_combobox;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
