/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc319_carreservation;

import CarReserve.CarReserveManagement;
import View.CarManagement;
import controller.MainApplicationController;
import controller.NewLoginController;
import edu.sit.cs.db.CSDbDelegate;
import java.util.ArrayList;
import java.util.HashMap;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author T.Chan
 */
public class MainApp extends javax.swing.JFrame {
    
    MainApplicationController mainAppCtrl;
    
    /**
     * Creates new form MainApp
     */
    public MainApp(MainApplicationController mainAppCtrl) {
        this.mainAppCtrl = mainAppCtrl;
        
        setTitle("Car Reserving System");
        setLook();
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_header = new javax.swing.JLabel();
        btn_reservation_system = new javax.swing.JButton();
        car_button = new javax.swing.JButton();
        add_servicer = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_header.setText("Car Reservation System");

        btn_reservation_system.setText("Car Reserve Management");
        btn_reservation_system.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_reservation_system.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservation_systemActionPerformed(evt);
            }
        });

        car_button.setText("Car Management");
        car_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        car_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_buttonActionPerformed(evt);
            }
        });

        add_servicer.setText("Add Service Provider");
        add_servicer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_servicerActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(add_servicer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(car_button))
                                    .addComponent(btn_reservation_system)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(label_header)))
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(label_header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btn_reservation_system, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(car_button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_servicer)
                    .addComponent(logout))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reservation_systemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservation_systemActionPerformed
        mainAppCtrl.runReservationWindow();
    }//GEN-LAST:event_btn_reservation_systemActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        new NewLoginController();
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void car_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_buttonActionPerformed
        mainAppCtrl.runCarManagementWindow();
    }//GEN-LAST:event_car_buttonActionPerformed

    private void add_servicerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_servicerActionPerformed
        /*ClerkAddPanel addServicer = new ClerkAddPanel();
        int value = JOptionPane.showConfirmDialog(null, addServicer, "Add Servicer", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if(value == JOptionPane.OK_OPTION){
            if( !(addServicer.getEmail().equals("") ||
                    addServicer.getPhoneNumber().equals("") ||
                    addServicer.getName().equals("") ||
                    addServicer.getLastname().equals("") ||
                    addServicer.getUsername().equals("") ||
                    addServicer.getPassword().equals("")) ){
                connectDB();
                String sql_insert = "INSERT INTO CAR_Officer VALUES('"
                        + addServicer.getUsername() + "','"
                        + addServicer.getPassword() + "','"
                        + addServicer.getName() + "','"
                        + addServicer.getLastname() + "','"
                        + addServicer.getEmail() + "','"
                        + addServicer.getPhoneNumber()
                        + "')";
                System.out.println(db.executeQuery(sql_insert));
                System.out.println(db.disconnect());
            } else {
                JOptionPane.showMessageDialog(null, "Invalid value!", "Error", JOptionPane.PLAIN_MESSAGE);
            }
        }*/
    }//GEN-LAST:event_add_servicerActionPerformed

    public void setLook(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_servicer;
    private javax.swing.JButton btn_reservation_system;
    private javax.swing.JButton car_button;
    private javax.swing.JLabel label_header;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
